package com.main.htarget;

// Generated 18/10/2013 01:29:53 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TipoFundamento generated by hbm2java
 */
public class TipoFundamento implements java.io.Serializable {

	private BigDecimal cveTipo;
	private String tipoFundamento;

	public TipoFundamento() {
	}

	public TipoFundamento(BigDecimal cveTipo, String tipoFundamento) {
		this.cveTipo = cveTipo;
		this.tipoFundamento = tipoFundamento;
	}

	public BigDecimal getCveTipo() {
		return this.cveTipo;
	}

	public void setCveTipo(BigDecimal cveTipo) {
		this.cveTipo = cveTipo;
	}

	public String getTipoFundamento() {
		return this.tipoFundamento;
	}

	public void setTipoFundamento(String tipoFundamento) {
		this.tipoFundamento = tipoFundamento;
	}

}
